### PR TITLE
Kirilogan dev patch 1

### PR DESCRIPTION
**Pull request by kirilogan**
- Can specify specific properties/alias as singleton
- Does not break on null, and will instead continue to next property

### CODE REVIEW

**Comment by afilina** [comment]
Give me some time to write test cases for the changes and then I'll merge. I'm volunteering for an event all day, so either later today or tomorrow.

**Comment by kirilogan** [comment]
No problem! Take your time, thought I'd contribute, awesome work btw!

**Comment by afilina** [comment]
Can you give me a realistic use case for this? I'm trying to add a proper test and documentation. Just give me an SQL query and what you're trying to achieve. Thanks!

**Comment by kirilogan** [comment]
Not quite what I'm using it for, but a simple example would be:

### person Table

Columns: personID, name, birth_countryID (Foreign key to Country Table)

### country Table

Columns: countryID, name, abbreviation

### Query Statement:

```
SELECT
  p.personID as persons__id,
  p.name as persons__name,
  c.countryID as persons__birthCountry__id,
  c.name as persons__birthCountry__name,
  c.abbreviation as persons__birthCountry__abbreviation
FROM person p
JOIN country c ON c.countryID = p.birth_countryID
```

### usage

```
$result = $fetch_nested_sql($statement,
   [
      'persons' => 'Person',
      'birthCountry' => 'Country',
   ],
   [
      'birthCountry'
   ]
);
```

### result

```
stdClass Object
(
    [persons] => Array
        (
            [1] => Person Object
                (
                    [id] => 1
                    [name] => John Doe
                    [birthCountry] => Country Object
                        (
                            [id] => 1
                            [name] => Canada
                            [abbreviation] => CA
                        )
                )
            [2] => Person Object
                (
                    [id] => 2
                    [name] => Jane Doe
                    [birthCountry] => Country Object
                        (
                            [id] => 2
                            [name] => United States of America
                            [abbreviation] => USA
                        )
                )
        )
)
```

### result without specifying singleton

```
stdClass Object
(
    [persons] => Array
        (
            [1] => Person Object
                (
                    [id] => 2
                    [name] => John Doe
                    [birthCountry] => Array
                        [1] => Country Object
                            (
                                [id] => 1
                                [name] => Canada
                                [abbreviation] => CA
                            )
                )
            [2] => Person Object
                (
                    [id] => 2
                    [name] => Jane Doe
                    [birthCountry] => Array
                        [2] => Country Object
                            (
                                [id] => 2
                                [name] => United States of America
                                [abbreviation] => USA
                            )
                )
        )
)
```

In the example below, the merged nestedsql would only return a single instance of the Country Class rather than returning an array of Country Classes. Person and Country have a many-to-one relationship in this situation/column; any given person would only have one country at which they were born.

Does that example work?

**Pull request merged**
